#!/bin/bash
echo "QKDISN Quantum Verification with 28-Qubit Advanced Circuit"
echo "=========================================================="
echo ""
echo "1. Clone QKDISN branch:"
echo "   git clone -b QKDISN https://github.com/shellworlds/TFIMTDMVEQ.git"
echo "   cd TFIMTDMVEQ"
echo ""
echo "2. Run 5-circuit verification:"
echo "   python3 quantum_verify.py RRMR"
echo ""
echo "3. See advanced 28-qubit circuit:"
echo "   python3 advanced_28q.py"
echo ""
echo "Or single command:"
echo "git clone -b QKDISN --depth=1 https://github.com/shellworlds/TFIMTDMVEQ.git && cd TFIMTDMVEQ && echo '=== 5 Circuits ===' && python3 quantum_verify.py RRMR && echo '' && echo '=== 28-Qubit ===' && python3 advanced_28q.py"
